In [48]:
from numpy.linalg import svd
import numpy as np
from numpy import zeros, ones, shape, dot, multiply

In [49]:
M = np.arange(1,7).reshape((2,3))
M

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
U,s,V=svd(M,full_matrices=0)
s = np.diag(s)

In [66]:
shape(U), shape(s), shape(V)

((2, 2), (2, 2), (2, 3))

In [67]:
# Original Matrix Reconstruction
dot(dot(U,s),V)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [68]:
# Low rank approximation
U = U[:,0]
s = s[0,0]
V = V[0,:]

In [70]:
M_low_rank = s*np.outer(U,V)
M_low_rank

array([[ 1.57454629,  2.08011388,  2.58568148],
       [ 3.75936076,  4.96644562,  6.17353048]])

In [69]:
s

9.5080320006957244

In [61]:
V

array([-0.42866713, -0.56630692, -0.7039467 ])