In [11]:
from numpy.linalg import svd
import numpy as np
from numpy import zeros, ones, shape, dot, multiply

In [36]:
M = np.arange(1,7).reshape((2,3))
M

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
U,s,V=svd(M,full_matrices=0)
s = np.diag(s)

In [44]:
shape(U), shape(s), shape(V)

((2, 2), (2, 2), (2, 3))

In [45]:
# Original Matrix Reconstruction
dot(dot(U,s),V)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [46]:
# Low rank approximation
U = U[:,0]
s = s[0]
V = V[0,:]

M_low_rank = dot(dot(U,s),V)
M_low_rank

array([ 1.57454629,  2.08011388,  2.58568148])